version: '3'
services:
  devops: hemanth9848/devopsrepo:latest
    image: 
    ports:
      - "80:80"
    deploy:
      replicas: 3

  aws:
    image: hemanth9848/awsrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  azure:
    image: hemanth9848/azurerepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
